rundeck/provider.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Fixes #22
Adds the argument for `schedule_enabled` and defaults it to `true`.

Add schedule_enabled job argument

---

rundeck/resource_job.go
rundeck/resource_job_test.go

Fixes #26 
In my experiments with the Rundeck UI and exporting to `yaml` and `xml` empty options don't get persisted. The API itself my persist and return the empty string in a list, however `required` is probably the correct argument to configure if the option doesn't need to be supplied.
This change produces the following:
```
* rundeck_job.example: 1 error(s) occurred:
* rundeck_job.example: Argument "value_choices" can not have empty values; try "required"
```

Gracefully handle empty value choice with error message

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Hi! I'm not 100% sure I did this right but the tests pass when I run them against my local instance. Some feedback here would be great. I have some meta-jobs which call other jobs overriding their node filters, so being able to define this in tf would be great for me. Thank you!
This adds:
1.  ability to override rerferenced job node filters
2. ability to let a job succeed even if no nodes were defined.

Allow overriding of job node filters

---

.travis.yml

This is no longer the way to test per this commit at Hashicorp: https://github.com/hashicorp/terraform-website/commit/6d41be434cf85392bc9de773d8a5a8d571a195ad

Remove website-test

---

.github/workflows/release.yml

This is a quick tweak to our `release` workflow for releasing to Terraform. As it is, it will only trigger publishing a new version if a new tag is _pushed_ to the repo. This change adds triggers so that it can be done both manually, and if a release is cut via the GH UI.

Add manual, publish triggers for updating in TF registry

---

rundeck/import_resource_project_test.go
rundeck/resource_project.go
website/docs/r/project.html.md

Based on https://github.com/rundeck/terraform-provider-rundeck/pull/50 with a small update (last commit)
This allows to import already existing projects from running Rundeck instances which makes migration to Terraform management easier.
Validate if that works:
- create a project in Rundeck via Terraform e.g. `my-test-project`
- create a backup of your `terraform.tfstate` (e.g. via `cp` or a local git)
- delete the `terraform.tfstate` file
- import the project via `terraform import rundeck_project.my_test_project my-test-project` 
- compare the diffirence between the new `terraform.tfstate` and the previous one - no actual configuration should change
It was requested in the other PR that documentation is provided. Please elaborate as that PR already contains addition to the documentation.

Ability to import projects

---

rundeck/job.go
rundeck/resource_job.go
website/docs/r/job.html.md

This is a continuation of #77 which I can not modify, unfortunately.
This PR adds the `retry_delay` option to the `rundeck_job` resource and documents it using the description found in the Rundeck UI.

Add retry delay option

---

website/docs/r/job.html.md

Scheduler format is not unix crontab, it's jquartz.

Update job.html.md - not unix crontab format

---

CHANGELOG.md
rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

This PR is a collection of work from @tebriel and @sorenmat adding Orchestrator options. (PR #58 and #29)
There was remaining work to merge fully:
[ ] Add the following Orchestrator options missing from this PR: 
[ ] Update Documentation to ensure the features are fully covered. (some was lost in merging this feature to a local branch due to conflicts.)

Orchestrator Options

---

rundeck/job.go
rundeck/resource_job.go
website/docs/r/job.html.md

Finalizing #114 from @dbrowneihg

Hidden option

---

rundeck/job.go
rundeck/resource_job.go

Internally Rundeck has two params to specify "script". When script specified as Url Rundeck use script_url param.

Add script_url param to Command.

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Log filter plugins are defined under a `plugins` element in the `command` element in the XML definition of a job. This contains a list of `LogFilter` elements that defined Log Filter plugins to add to the step. This MR adds support for them and allows one to create Rundeck jobs with Log Filter plugins applied to its workflow steps. It also includes an acceptance test and documentation showing a typical use case for it.

Fix log filter plugins

---

CHANGELOG.md
rundeck/import_resource_job_test.go
rundeck/resource_job.go
rundeck/resource_job_test.go

Trying to revive https://github.com/rundeck/terraform-provider-rundeck/pull/44, by fixing the conflicts, testing it, and fixing the acceptance tests.
A use case for this would be transitioning from an existing manual Rundeck configuration into a Terraform-driven one using importing and automatic config generation (useful links: https://opentofu.org/docs/language/import/ and https://opentofu.org/docs/language/import/generating-configuration/)

Add support for importing jobs into the Terraform state

---

CHANGELOG.md
rundeck/import_resource_job_test.go
rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Collection of Community Pull Requests that include the following functionality.
- Added Job step option for `script_url`
- Added ability to reference jobs in other projects through the use of `project_name` in `job` command type.
- Added support for Log Filters on individual Job Steps
- Added Import capability for Job Definitions

0.4.8 - Collection of updates

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

This request adds the missing four flags that are available when adding a reference job step in a Rundeck command. This should solve #127 
I added a test that should validate the added flags and the earlier added reference project name. I tested the provider, but I could not get the included tests running. It could be that this test still fails, while the new flags function as expected.

Added additional reference job flags

---

CHANGELOG.md
rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Merges #140 to Main.
thank you @b0tting

Job ref flags

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

Right now, there is no support for setting the option type as shown in the docs: https://docs.rundeck.com/docs/manual/jobs/job-options.html#file-option-type. The option type is thus forced to `text` for all options. This MR adds a type field to the JobOption definition and adds support to allow the user to specify the option type, defaulting to `text`

Add support for setting options types (file or text)

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

This PR adds support for setting log limits on Rundeck jobs in the Terraform provider. The new attribute `log_limit` allows users to configure log output limits, define actions to take when these limits are reached, and specify custom status.
- `log_limit` attribute for Rundeck jobs to manage logging behavior.
- **output**: Maximum total line-count or size of the log.
- **action**: The action to take when the log limit is reached (`halt` or `truncate`).
- **status**: Custom status for halted jobs due to log limits.
```hcl
resource "rundeck_job" "example_with_log_limit" {
name              = "Example Job with Log Limit"
project_name      = rundeck_project.terraform.name
description       = "An example job with log limit settings"
log_limit {
output = "100MB"
action = "halt"
status = …
```

feat(job): add logging limits

---

rundeck/resource_job.go

Fix for https://github.com/rundeck/terraform-provider-rundeck/issues/153 as intended in PR https://github.com/rundeck/terraform-provider-rundeck/pull/154
Problem:
When creating a new job via Terraform, if the nodes_selected_by_default option was not set to true, the job would fail to execute locally, as it could not find any nodes.
Solution:
To align with the behavior of the GUI, the nodes_selected_by_default option was modified to have a default value of true.

Set nodes_selected_by_default to true

---

vendor/github.com/rundeck/go-rundeck/rundeck/client.go

**Description** 
This change adjusts the HTTP response handling in the Go client for the Rundeck provider by removing the acceptance of HTTP 409 (Conflict) as a valid response code.
**Changes:**
Removed http.StatusConflict from the list of accepted status codes in azure.WithErrorUnlessStatusCode.
Responses with a 409 status code will now result in an error, aligning the behavior with expected operation flows.
**Impact**
Enhances the robustness of the client by treating conflicts as failures instead of proceeding as if they were successes.
Reduces the likelihood of misinterpreting a conflict as an expected outcome.
Testing
**Validated the following scenarios:**
Responses with 200 (OK) and 201 (Created) are still correctly accepted.
Responses  other than 200 and 201 now raise an error, as …

Check valid status code on ProjectCreateResponder to validate proyect

---

rundeck/resource_job.go
website/docs/r/job.html.md

**This PR addresses two issues introduced in**
[PR #159](https://github.com/rundeck/terraform-provider-rundeck/pull/159)
[PR #160](https://github.com/rundeck/terraform-provider-rundeck/pull/160)
**log_limit Block Behavior**
Previously, the log_limit block was updated to allow optional fields (output, action, status). However, when any of these fields were omitted, their values defaulted to null. This caused Terraform to consistently detect pending updates for the resource, even if there were no actual changes. As a result, unnecessary updates were repeatedly applied.
**Resolution**
log_limit remains optional, but all fields within it (output, action, status) are now required.
This change ensures that the values in the Terraform configuration always match those in Rundeck, resolving the …

Fix: Resolve log_limit and nodes_selected_by_default update issues in Terraform Rundeck provider

---

rundeck/resource_project.go

**Description**
This change introduces validation in the CreateProject function of the Go client for the Rundeck provider to ensure a project with the same name does not already exist before attempting to create it.
**Changes**
Added a call to client.ProjectGet(ctx, name) to check if a project with the given name already exists.
If the project's status code is not 404 (indicating it exists), the function now returns an error with a descriptive message.

Check project name before creating it

---

rundeck/job.go
rundeck/resource_job.go

Closes #167.
We need to choose on which runner the job will be run and this is not supported by this plugin, it seems only the node choice is supported.
I suggest adding these fields :
```
runner_selector_filter
runner_selector_filter_mode
runner_selector_filter_type
```
Which correspond to the XML field `runnerSelector`:
```xml
<runnerSelector>
<filter>my_filter</filter>
<runnerFilterMode>TAGS</runnerFilterMode>
<runnerFilterType>TAG_FILTER_AND</runnerFilterType>
</runnerSelector>
```

Support job runner selector

---

test/Dockerfile
test/remco/resources.d/xmlLegacy.toml
test/remco/templates/xmlLegacy.properties

This pull request updates the Rundeck base image to a newer version and adds support for enabling the legacy XML API, which is useful for compatibility with certain tools like Terraform. Below are the key changes:
* Updated the Rundeck base image in `test/Dockerfile` from version `3.3.6` to `5.11.1` to use the latest features and improvements.
* Added a new template configuration in `test/remco/resources.d/xmlLegacy.toml` to generate properties for enabling the legacy XML API.
* Introduced a new template file `test/remco/templates/xmlLegacy.properties` with the setting `rundeck.feature.legacyXml.enabled=true` to enable the legacy XML API for compatibility with Terraform.

chore(docker): update dockerfile to use rundeck version 5.11.1

---

rundeck/job.go
rundeck/resource_job.go
rundeck/resource_job_test.go
website/docs/r/job.html.md

This pull request introduces support for configuring webhook notifications in Rundeck jobs, including specifying payload formats and HTTP methods. Key changes include updates to the `Notification` struct, enhancements to the Terraform provider schema, and the addition of new tests and documentation.
* **`rundeck/job.go`**: Added `Format` and `HttpMethod` fields to the `Notification` struct to allow specifying the webhook payload format (`json` or `xml`) and the HTTP method (`post` or `get`).
* **`rundeck/resource_job.go`**:
- Updated the Terraform provider schema to include `format` and `http_method` fields under the `notification` block.
- Modified the `jobFromResourceData` function to map `format` and `http_method` values from resource data to the `Notification` struct.
- Enhanced the …

feat(jobs): add format and http_method to notification
